services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - express
    env_file:
      - .env

  express:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
