#root docker-compose.yaml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Backend service exposed on port 3001
    env_file:
      - .env
   

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Frontend service exposed on port 3000
    depends_on:
      - backend
    env_file:
      - .env
  

  

  db:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lifeishell.69
      MYSQL_DATABASE: my_bank
      MYSQL_USER: root
      MYSQL_PASSWORD: Lifeishell.69
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
