services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - express
    env_file:
      - .env

  express:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lifeishell.69
      MYSQL_DATABASE: my_bank
      MYSQL_USER: root
      MYSQL_PASSWORD: Lifeishell.69
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
